export const products = [
  {
    id: 1,
    img: "https://images.unsplash.com/photo-1611510338559-2f463335092c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=764&q=80",
    link: "https://nike-store-clone-jet.vercel.app/",
    title: "Nike Website Clone",
    desc: "Nike webiste build using React, Tailwind CSS and deploy on Vercel",
  },
  {
    id: 2,
    img: "https://images.unsplash.com/photo-1644329843491-99edfc83de04?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
    link: "https://taskappfrontend.onrender.com",
    title: "Task App",
    desc: "Task app allows users to add, delete and switch task.",
  },
  {
    id: 3,
    img: "https://images.unsplash.com/photo-1488998287214-1e668a8e0dc4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://chatappbyanup.netlify.app/",
    title: "Real Chat App",
    desc: "Real chat application build using Socket.IO, deployed server side on heroku and client side on netlify",
  },
  {
    id: 4,
    img: "https://images.unsplash.com/photo-1432821596592-e2c18b78144f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://my-blog-anup-poudel.vercel.app/",
    title: "Blog App",
    desc: "This is blog app build using React , GraphQL, NextJS and Tailwind CSS",
  },
  {
    id: 5,
    img: "https://images.unsplash.com/photo-1600007283728-22abc97b9318?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80",
    link: "https://expensetrackerbyanup.netlify.app/",
    title: "Expense Tracker App",
    desc: "Manage your expenses and saving.",
  },
  {
    id: 6,
    img: "https://images.unsplash.com/photo-1504270997636-07ddfbd48945?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80",
    link: "https://mysocialapp.onrender.com/",
    title: "Social Media App",
    desc: "Like/Unlike post, Follow/Unfollow other user, CRUD post and profile data, Forgot/Reset/Update password.Mobile Responsive.",
  },
  {
    id: 7,
    img: "https://blog.jetadmin.io/content/images/2019/12/image-3.png",
    link: "https://estore-1rqj.onrender.com/",
    title: "E-commerce Website",
    desc: "Overlay navbar, Stripe, React/Redux, NodeJS and MongoDb",
  },
];
